### ISSUE TITLE
Result load returns 500.

### ISSUE THREAD

**Issue by roger-mahler** [humlab-sead/sead_query_api#22]
This request payload gives a 500:
```json
{
  "facetsConfig": {
    "requestId": 1,
    "requestType": "populate",
    "targetCode": "sites",
    "triggerCode": "sites",
    "facetConfigs": [
      {
        "facetCode": "sites",
        "position": 1,
        "picks": [],
        "textFilter": ""
      }
    ]
  },
  "resultConfig": {
    "requestId": 1,
    "sessionId": "1",
    "viewTypeId": "map",
    "aggregateKeys": [ "site_level" ]
  }
}
```

**Comment by roger-mahler** [comment]
Error log:
```
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action SeadQueryAPI.Controllers.ResultController.Load (sead.query.api) in 268.5617ms
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLQ6949RLM2N", Request id "0HLQ6949RLM2N:00000002": An unhandled exception was thrown by the application.
Newtonsoft.Json.JsonSerializationException: Error setting value to 'FacetConfigs' on 'SeadQueryCore.FacetsConfig2'. ---> SeadQueryCore.QuerySeadException:                                                                                                 FacetConfig with null Facet not allowed
   at SeadQueryCore.FacetsConfigSpecification.IsSatisfiedBy(List`1 configs) in /src/sead.query.core/Model/FacetsConfig/FacetsConfigSpecification.cs:line 55
   at SeadQueryCore.FacetsConfig2.set_FacetConfigs(List`1 value) in /src/sead.query.core/Model/FacetsConfig/FacetsConfig2.cs:line 46
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerCont                                                                                                ract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonPrope                                                                                                rty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty membe                                                                                                r, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at SeadQueryAPI.Controllers.ResultController.Load(JObject data) in /src/sead.query.api/Controllers/ResultController.cs:line 51
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor                                                                                                , Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 317.6186ms 500

```
